### ISSUE TITLE
issue - demo1

### ISSUE THREAD

**Issue by GiuseppeArbore** [pettykanon/02-Kiruna-Explorer#1]
You've done a great job making your application very user-friendly! 
We have a few suggestions for further improvement:
- The button to save the area/point selection is hard to find due to its color.
- After a user selects a point on the map, the feedback message displays "Area" instead of "Point."
- The map opens in full-screen mode by default, which can be problematic if the user has multiple windows open on the screen."
- There is no indicator on the dashboard to show that the user is logged in.

**Comment by pettykanon** [comment]
Thanks for your feedback, we appreciate it.
Fixes done!
